version: '3.4'

services:
  mongo: 
      image: mongo
      ports:
        - 27017:27017
      restart: always
  backend:
      depends_on:
        - "mongo"
      image: backend
      build: ./backend
      ports: 
        - 3001:3001
      environment:
        - SERVER_PORT=3001
        - MONGO_URI=mongodb://mongo:27017
  front:
    depends_on:
      - backend
    image: front
    build: ./front
    ports:
      - 80:80
