version: '3.4'

services:
  mongodb: 
      image: mongo:latest
      ports: 27017:27017
  back:
      depends_on:
        - mongodb
      image: back
      build: ./backend/Dockerfile
      environment:
        NODE_ENV: development
      ports: 3001:3001
      command: ["node", "./dist/src/server.js"]
  front:
    depends_on:
      - back
    image: front
    build:
      context: front
      dockerfile: ./front/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
